### ISSUE TITLE
Release 2.0.4

### ISSUE THREAD

**Issue by WickedShell** [peterschwarz/clj-serial#12]
Not to nag, but can 2.0.4 be released as stable at this point? It's been tagged as snapshot for quite awhile, and I've been finding the snapshot to be perfectly stable in production at this point, with some useful additions in it.

**Comment by WhittlesJr** [comment]
I'm needing a release pretty badly as well.

**Comment by WhittlesJr** [comment]
Is there anything still holding this up? Anything I can help with?

**Comment by WhittlesJr** [comment]
Can be closed (2.0.5 is released)
